name: CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  validate:
    uses: swift-library/.github/.github/workflows/swift-package-ci.yml@ad683fc5f2aea7f9b78e0cc4a8e88895e72fadec
