name: CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  validate:
    uses: swift-library/.github/.github/workflows/swift-package-ci.yml@20a14023f84411951787364d3475961a68e098bb
